### ISSUE TITLE
Moving trained model between devices

### ISSUE THREAD

**Issue by jegork** [huggingface/setfit#206]
Hello!
Is there a way to move the trained SetFit model to another device?
E.g. I train a model on a GPU, and after initializing the model on a CPU-only machine I get 
`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

I have managed to fix the error by running:

```python
model.model_body = model.model_body.to("cpu")
model.model_head = model.model_head.to("cpu")
```

However, I guess it depends on the type of the head (in case of the Logistic regression head there is no need to move it).

If there is no single method to move a model between devices, shall I open a PR?

**Comment by blakechi** [comment]
Hi @jegork,

Thanks for raising this issue up!

Ya, I think by simply adding a `to` function for `SetFitModel` can fulfill your needs. But I think there might have something we need to fix due to the error you mentioned. Could you provide more details on how you initializing the model? Or maybe provide a snippet to reproduce the error? Thanks!

**Comment by jegork** [comment]
Hey @blakechi

I've fine-tuned a SetFit model, that was initialized using:
```python
SetFitModel.from_pretrained(
            model_name,
            use_differentiable_head=True,
            head_params={"out_features": 32},
        )
``` 

Afterwards, I've saved it using `.save_pretrained` and loaded into HF hub. Later I've initialized it again using same code above, and it lead me to this error. I fixed it by moving both head and body to CPU and saving and uploading it again to HF hub, which solved the issue.

**Comment by blakechi** [comment]
Thank you for your detailed explanation! I guess the error raised because of the initialization method of SetFitHead. Will validate my guess shortly.

Thanks again for raising this up!

**Comment by jegork** [comment]
@blakechi 
Apparently, there is something with the way that joblib serializes the torch head weights. Because I see that in SetFitModel it is loaded via `joblib.load`, which leads to the error.

However, it should work fine if you load the same file using `torch.load`.
But using `torch.load("model_head.pkl", map_location=torch.device("cpu"))`, I get the same error

**Comment by jegork** [comment]
I think the only way is to either pass the head type (sk/torch) into the config .json or rely on the extension of the head file (.bin for torch and .pkl for sk) and save/load respectively using joblib/torch. I can add a PR this week if we can come to an agreement on how to make it best :)

**Comment by JackMurphy97** [comment]
I have also come across this exact issue - it would be awesome to have some [.to(device)](url) functionality for the SetFitModel class!

**Comment by jegork** [comment]
@connormeaton unfortunately the problem was only addressed partly, and indeed the problem you mentioned have not been solved.

The only solution AFAIK, is to load the mentioned model on a GPU-enabled machine, then do

```python
model = model.to("cpu")
```

and then save again, which would result in a model that contains CPU weights, not cuda weights
