### ISSUE TITLE
Model trained on GPU can't be loaded on CPU-only instance

### ISSUE THREAD

**Issue by tomaarsen** [huggingface/setfit#276]
_Originally posted by @connormeaton in https://github.com/huggingface/setfit/issues/229#issuecomment-1385983238_

I found my way to this page because I am having trouble running a setfit model locally on cpu (I trained on a GPU instance, saved with joblib). I believe this PR attempts to solve this issue. How do I use this code to run my gpu trained model on cpu?

Here is my save code:
```
joblib.dump(trainer, 'model.joblib')
```
Here is my error when running:
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

I get the same error when loading both of the ways below:
```
new_trainer = joblib.load('model.joblib')
torch.load('model.joblib', map_location='cpu')
torch.load('model.joblib', map_location=torch.device('cpu'))
```

_Originally posted by @connormeaton in https://github.com/huggingface/setfit/issues/229#issuecomment-1385983238_

**Comment by tomaarsen** [comment]
@connormeaton Hello!

I don't have a great solution for you at this time, but I may have a hack. If you still have access to the GPU machine on which you trained, you may be able to load the model there, then move it to CPU, and save it again. The new saved model should be loadable on your CPU device.

That said, I believe that this is something that should be addressed by SetFit. I imagine there are many SetFit models on the Hub that were trained and saved on a GPU, and I want to ensure that they can be loaded on CPU-only devices. I'm not 100% sure that this is currently an issue, but it's good to verify nonetheless.

- Tom Aarsen

**Comment by connormeaton** [comment]
Hi @tomaarsen, thank you for the quick reply! How do I move the model to CPU when on my GPU machine? What command do you recommend? Thank you.

**Comment by tomaarsen** [comment]
I recommend [`SetFitModell.to`](https://github.com/huggingface/setfit/blob/f777c2c60b270604dae0dc1db4eea815e8c9019d/src/setfit/modeling.py#L413-L427), e.g.
```python
# Load the model
model = ...

# Move the model to CPU
model.to("cpu")

# Save the model
model.save_pretrained("my_directory")
```
For saving and loading you can try out your approaches too, they might work just fine too. I believe the "recommended" approach is to use [`SetFitModel.save_pretrained`](https://huggingface.co/docs/huggingface_hub/v0.10.1/en/package_reference/mixins#huggingface_hub.ModelHubMixin.save_pretrained) and [`SetFitModel.from_pretrained`](https://huggingface.co/docs/huggingface_hub/v0.10.1/en/package_reference/mixins#huggingface_hub.ModelHubMixin.from_pretrained).

**Comment by connormeaton** [comment]
Thanks. I tried this but I got an error:

```
model = joblib.load('huggingface_setfit_spaffNLP_01722.joblib')

# Move the model to CPU
model.to("cpu")

# Save the model
model.save_pretrained("my_directory")
```

and this gave me:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 2
      1 # Move the model to CPU
----> 2 model.to("cpu")
      4 # Save the model
      5 model.save_pretrained("my_directory")

AttributeError: 'SetFitTrainer' object has no attribute 'to'
```

I see my model is a `SetFitTrainer` object, not a `SetFitModel`. Is this the problem?

Here is how I trained and created the model:
```
model_id = "sentence-transformers/paraphrase-mpnet-base-v2"
model = SetFitModel.from_pretrained(model_id)
trainer = SetFitTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    loss_class=CosineSimilarityLoss,
    num_iterations=20,
    column_mapping={"sentence": "text", "label": "label"},
)
trainer.train()
joblib.dump(trainer, 'model.joblib')

```
FYI I was using joblib.dump to save my model because I would get the error `SetFitTrainer object has no method `save_pretrained`. Where did I go wrong?

**Comment by tomaarsen** [comment]
The `to`, `save_pretrained` and `from_pretrained` methods only work on a `SetFitModel` instance, not a `SetFitTrainer` instance. You can access the model that the Trainer has trained with the `model` attribute on the `SetFitTrainer`.
```python
trainer = joblib.load('huggingface_setfit_spaffNLP_01722.joblib')

# Move the model to CPU
trainer.model.to("cpu")

# Save the model
trainer.model.save_pretrained("my_directory")
```
Hopefully that does work :)

**Comment by connormeaton** [comment]
I understand, I missed that portion. However, I still get this error:
```
trainer = joblib.load('model.joblib')

# Move the model to CPU
trainer.model.to("cpu")

# Save the model
trainer.model.save_pretrained("dir")
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 4
      1 # model = joblib.load('huggingface_setfit_spaffNLP_01722.joblib')
      2 
      3 # Move the model to CPU
----> 4 trainer.model.to("cpu")
      6 # Save the model
      7 trainer.model.save_pretrained("dir")

AttributeError: 'SetFitModel' object has no attribute 'to'
```

If useful:
```
import setfit
print(setfit.__version__)
0.5.0
```

**Comment by tomaarsen** [comment]
Oh, you're very right. The `to` method was introduced to the repository one day after the 0.5.0 release, and we have not pushed a release since then. No stress, though. The following should be equivalent for your situation:
```python
# The following is equivalent to `model.to("cpu")` if the model head is an Sklearn LogisticRegression instance
trainer.model.model_body = trainer.model.model_body.to("cpu")
```
You can probably imagine now why we thought it was a good idea to introduce a concise method for that, hah!

**Comment by connormeaton** [comment]
Thank you. I ran this code and then saved the model with `to_pretrained'. 
```
trainer.model.to_pretrained("model")
```
Now I am attempting to load on my CPU machine with:
```
model = SetFitModel.from_pretrained('model')
```
but I get this error:
```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: ...
```
I also tried:
```
model = SetFitModel.from_pretrained('model', local_files_only=True)
```
and got this error:
```
ValueError: Cannot find the requested files in the cached path and outgoing traffic has been disabled. To enable model look-ups and downloads online, set 'local_files_only' to False.
```

I do not want to use the huggingface hub. I'd like to just download the model to my local machine and run it there. Is that possible?

**Comment by tomaarsen** [comment]
I assume that you're referring to `save_pretrained` rather than `to_pretrained`. Beyond that, can you confirm that there is indeed a folder named `model` accessible from the loading script?

For example:
```python

from pathlib import Path
from setfit import SetFitModel

# Determine whether the model folder exists locally
model_directory_name = "model"
assert Path(model_directory_name).exists(), f"Model cannot be found on the disk at location {model_directory_name!r}"

# Load the model from disk
model = SetFitModel.from_pretrained(model_directory_name)

# Run inference
preds = model(["i loved the spiderman movie!", "pineapple on pizza is the worst 🤮"])
print(preds)
```
For me, saving the model produces a directory like so:
![image](https://user-images.githubusercontent.com/37621491/213190826-c70a7e2d-3b88-4d89-9fbf-a8856496c2f5.png)

Which I can correctly load using the script above.

As for your final question: Yes, that is possible. It should be possible using `save_pretrained` and `from_pretrained`.

**Comment by connormeaton** [comment]
Getting close. I used `to_pretrained` instead of `save_pretrained`. I resaved the model with `save_pretrained`.

I downloaded locally. The model dir looks like yours. I ran the assert and it passed. I now get this:

```
Traceback (most recent call last):
  File "src/nlp/predict_utterances_setfit.py", line 12, in <module>
    model = SetFitModel.from_pretrained(model_directory_name)
  File "/Users/connoreaton/mediapipe/lib/python3.8/site-packages/huggingface_hub/hub_mixin.py", line 182, in from_pretrained
    return cls._from_pretrained(
  File "/Users/connoreaton/mediapipe/lib/python3.8/site-packages/setfit/modeling.py", line 391, in _from_pretrained
    model_head = joblib.load(model_head_file)
  File "/Users/connoreaton/mediapipe/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/connoreaton/mediapipe/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/usr/local/Homebrew/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 32
```

I can try retraining the model and saving directly with save_pretrained instead of the original joblib save/loaded model?

**Comment by tomaarsen** [comment]
That might be worth a shot.

**Comment by connormeaton** [comment]
No change. I retrained the model and performed all the recommended steps. Same error:

```
Traceback (most recent call last):
  File "src/nlp/predict_utterances_setfit.py", line 12, in <module>
    model = SetFitModel.from_pretrained(model_directory_name)
  File "/Users/connoreaton/mediapipe/lib/python3.8/site-packages/huggingface_hub/hub_mixin.py", line 182, in from_pretrained
    return cls._from_pretrained(
  File "/Users/connoreaton/mediapipe/lib/python3.8/site-packages/setfit/modeling.py", line 391, in _from_pretrained
    model_head = joblib.load(model_head_file)
  File "/Users/connoreaton/mediapipe/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/connoreaton/mediapipe/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/usr/local/Homebrew/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 32
```

**Comment by connormeaton** [comment]
It works now! My GPU instance had joblib 1.2.0 and my local CPU machine had 1.1.0. After updating joblib, the recommendations you made work. Thank you for all of your help.

**Comment by tomaarsen** [comment]
Wonderful! I'll keep this open, as I do want to investigate loading GPU models on CPU-only devices. Our workaround clearly won't work for users who do not have a GPU device with which they can create a GPU version of the model.

I'm glad I could help!

**Comment by doubianimehdi** [comment]
Hi,

I didn't get how it was resolved ... I have folders with all the json , pkl and bin files and trained them on gpu, how do I load it on CPU ? please advice ...

**Comment by tomaarsen** [comment]
Hello,

This was not resolved. We are open to help here.
A workaround right now is to load the models on a GPU-enabled device, move them to CPU, and then save them again, as described above. You may have success using Google Colab for this, if you do not have a GPU-enabled device with enough VRAM available.

I'll label this issue accordingly.

- Tom Aarsen

**Comment by hoagie18** [comment]
For those still coming across this, setfit 0.6.0 supports `model.to(device)`. You should just need to update your setfit: `pip install setfit --upgrade`.

I successfully moved my trained, saved model from cuda to cpu using the following code:
```
from setfit import SetFitModel
model = SetFitModel.from_pretrained('my_setfit_model')
model.to('cpu')
model.save_pretrained('my_setfit_model_cpu')
```

And code to load and predict on my cpu machine:
```
from setfit import SetFitModel
model = SetFitModel.from_pretrained('my_setfit_model')
text = ['my sample text']
prediction = model.predict(text)
```

I found the cpu machine also needs to be on setfit >= 0.6.0, otherwise you'll get errors when loading the model.

**Comment by lsmith77** [comment]
If you are seeing `TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'` then you are missing https://github.com/huggingface/setfit/commit/884da4d609e7e66306c756e133b0a43b38e2f724

**Comment by naman-TI** [comment]
Hi @tomaarsen 

I've tried to move the model to cpu before saving to avoid CUDA out of memory error. But still running into the same error. This is the snippet

```
    ## load the model in int8
    model = AutoModelForCausalLM.from_pretrained(
        args.model_name, load_in_8bit=True, device_map={"": Accelerator().process_index}
    )

    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=val_data,
        tokenizer=tokenizer,
        peft_config=lora_config,
        packing=True,
        max_seq_length=args.seq_length,
    )
  
    print("Training...")
    trainer.train()

    print("Moving the model to CPU memory before saving")
    trainer.model = trainer.model.to("cpu")
    print(next(trainer.model.parameters()).device)

    print("Saving the last checkpoint of the model")
    trainer.model.save_pretrained(os.path.join(args.output_dir, "final_checkpoint/"))
```
I've run out of ideas and not sure where I'm going wrong.

**Comment by naman-TI** [comment]
@tomaarsen Yes it is, though I'm assuming from looking at the source code in TRL that it should behave the same

**Comment by tomaarsen** [comment]
I'm afraid that they're fairly different codebases. I would advise opening an issue on the [TRL](https://github.com/lvwerra/trl) repository instead.

**Comment by smart-patrol** [comment]
Looks like the save as CPU the then load works. I am using it to save the reload to cuda.
Interesting though that when it errors it calls out `torch.load` with a `map_location` for cpu...

**Comment by davidsbatista** [comment]
Is still the only practical solution to load the model on a GPU machine, move it to CPU and the save it?

and, is there already an on-going idea branch on how to solve this - I could help if needed.

**Comment by tomaarsen** [comment]
When #439 is merged, then models will always be moved to CPU before they're saved. Such a model should then be loadable on non-CUDA devices as well.
